repos:
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3.10
      stages: [commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args: [--per-file-ignores=__init__.py:F401]
      stages: [commit]
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      language: system
      entry: pytest -v
      always_run: true
      pass_filenames: false
      stages: [commit]
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'venv/bin/pip3 freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]